- hosts: localhost
  connection: local

  vars_prompt:
     - name: "vm_name"
       prompt: "Enter the name of the virtual machine"
       private: no

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
   
    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        validate_certs: no
        folder: /new_virtual_machines
        #name: test_vm_0001
        name: "{{ vm_name }}"
        state: poweredon
        guest_id: centos64Guest
        # This is hostname of particular ESXi server on which user wants VM to be deployed
        esxi_hostname: "{{ esxi_hostname }}"
       # esxi_hostname: 192.168.1.201
        disk:
        - size_gb: 20
          type: thin
          datastore: "{{ datastore }}"
         #datastore: hitachi-datastore
        hardware:
          memory_mb: 512
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          type: dhcp
         #mac: aa:bb:dd:aa:00:14
         #ip: 10.10.10.100
         #netmask: 255.255.255.0
          device_type: vmxnet3
       #wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy_vm
