#=> Create a new VMware protection Job to protect only a set of VMs given in the inventory
---
  - hosts: local
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Protection job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          cohesity_server: 10.2.144.28
          cohesity_admin: "{{ username }}"
          cohesity_password: "{{ password }}"
          cohesity_validate_certs: False
          cohesity_protection:
              state: present
              job_name: protect_vcenter
              storage_domain: "DefaultStorageDomain"
              policy: "Bronze"
              sources:
                - endpoint: "vcenter_ip_or_hostname"
              environment: "VMware"
              include: "{{ groups['include_vms'] }}"
