#=> Create a file based protection job for all linux sources
---
  - hosts: local
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Protection job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          cohesity_server: 10.22.149.28
          cohesity_admin: "{{ username }}"
          cohesity_password: "{{ password }}"
          cohesity_validate_certs: False
          cohesity_protection:
              state: present
              job_name: "protect_vm"
              storage_domain: "DefaultStorageDomain"
              sources:
                - endpoint: "{{ item }}"
                  paths:
                    - includeFilePath: "/home"
                      excludeFilePaths:
                        - "/home/cohesityagent"
                      skipNestedVolumes: False
              environment: "PhysicalFiles"
        with_items: "{{ groups['linux'] }}"
