#=> Create a new VMware protection job
---
  - hosts: local
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Protection job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          cohesity_server: 10.2.148.33
          cohesity_admin: "{{ username }}"
          cohesity_password: "{{ password }}"
          cohesity_validate_certs: False
          cohesity_protection:
              state: present
              job_name: protect_vcenter
              storage_domain: "DefaultStorageDomain"
              policy: "Gold"
              sources:
                - endpoint: "vcenter_ip_or_hostname"
              environment: "VMware"
