---
- name: "Cohesity Protection Source: Set {{ cohesity_source.endpoint | default('endpoint') }} to state of {{ cohesity_source.state | default('present') }}"
  cohesity_source:
    cluster: "{{ cohesity_server }}"
    username: "{{ cohesity_admin }}"
    password: "{{ cohesity_password }}"
    validate_certs: "{{ cohesity_validate_certs | default(False) }}"
    state: "{{ cohesity_source.state | default('present') }}"
    endpoint: "{{ cohesity_source.endpoint | default('') }}"
    environment: "{{ cohesity_source.environment | default('Physical') }}"
    host_type: "{{ cohesity_source.host_type | default('Linux') }}"
    vmware_type: "{{ cohesity_source.vmware_type | default('VCenter') }}"
    source_username: "{{ cohesity_source.source_username | default('') }}"
    source_password: "{{ cohesity_source.source_password | default('') }}"
    nas_protocol: "{{ cohesity_source.nas_protocol | default('NFS') }}"
    nas_username: "{{ cohesity_source.nas_username | default('') }}"
    nas_password: "{{ cohesity_source.nas_password | default('') }}"
  tags: always
