---
 - hosts: all
   tasks:
      - user: 
         name: root
         password: $6$kjS5.fV6l21cs7W/$fVpnoSthaQLICahVea.lL9pYyw2/WtXVJBO5hScf.HsR6H2R2GaZwxb1VdtzFbsla4HWFwnz4AyVUAwNBV6ii0
         state: present
         update_password: always

      - user:
         name: administrator
         comment: "Administrator"
         shell: /bin/bash
         group: wheel
         password: $6$kjS5.fV6l21cs7W/$fVpnoSthaQLICahVea.lL9pYyw2/WtXVJBO5hScf.HsR6H2R2GaZwxb1VdtzFbsla4HWFwnz4AyVUAwNBV6ii0
         state: present
         update_password: always

      - user:
         name: jbdummy
         comment: "Joe Bob Dummy"
         shell: /bin/bash
         uid: 20003
         password: $6$kjS5.fV6l21cs7W/$fVpnoSthaQLICahVea.lL9pYyw2/WtXVJBO5hScf.HsR6H2R2GaZwxb1VdtzFbsla4HWFwnz4AyVUAwNBV6ii0
         state: present
         update_password: on_create

      - user: 
         name: hhakeem    
         comment: "Hamzah Hakeem"
         shell: /bin/bash
         groups: wheel
         password: $6$NIZt6vfFl24SWx7a$kUfumH9XbSUgHOPcuW8uyCzUCeNzmyJ7jpMxA8MCt9XGP9ycyyAE4wFybYZ4VHT0v6dM0kzhpPnsoO7DFxBzA1
         state: present
         update_password: always  
