---
 - hosts: all
   tasks: 
      - service:
          name: postfix
          enabled: yes
          state: started
          
      - service:
          name: httpd
          enabled: yes
          state: started

