---
 - hosts: all
   tasks: 
     # - name: change hostname
      #  hostname: name="{{ hostname }}"

      - name: epel-install
        yum: name=epel-release state=present update_cache=yes
    
      - name: system updates
        yum: name=* state=latest update_cache=yes
       
